.github/release-drafter.yml
.github/workflows/ci.yml
.github/workflows/container-build.yml
.github/workflows/fossa.yml
.github/workflows/openssf.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/reusable-container-image.yml
.golangci.yml
CODEOWNERS
Dockerfile
LICENSE
Makefile
cmd/root.go
internal/log/level.go
internal/policies/fetcher.go
internal/policies/fetcher_test.go
internal/policies/filter_test.go
internal/resources/fetcher.go
internal/resources/fetcher_test.go
internal/scanner/scanner.go

Fix https://github.com/kubewarden/audit-scanner/issues/5
Yes please.
At the end, ended up lifting the approach from kubewarden-controller, with renaming.
Successful container build job run in my fork, https://github.com/viccuad/audit-scanner/pkgs/container/audit-scanner.
release-drafter needs its config in main prior to working.
TODO:
- fossa needs `secrets.FOSSA_API_TOKEN`
- openssf needs adding the labels to readme after first job run
- before release, uncomment the relevant golangci-lint linters under TODO

feat: Add CI & CD

---

Makefile
cmd/root.go
go.mod
internal/resources/admission_request.go
internal/resources/admission_request_test.go
internal/resources/fetcher.go
internal/resources/fetcher_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Updates the audit scanner to send the AdmissionReview built with the previously fetched resources to the policy server.
Fix #10 
```shell
make unit-tests
```
To run in a actual cluster follow the step defined [here](https://github.com/kubewarden/audit-scanner/pull/2) and then run this code. If you want to run the scanner using a Kubernetes deployment these are some example of the files you can use:
RBAC used to run the deployment:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: audit-scanner
namespace: kubewarden
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: kubewarden-audit-scanner
rules:
- apiGroups:
- ""
resources:
- "*"
verbs:
- list
- get
- watch
- apiGroups:
- "apps"
resources:
- "*"
verbs:
- list
- get
- watch
- apiGroups:
- …
```

Send audit AdmissionReview request to policy server.

---

.github/workflows/release.yml
.gitignore

Partially implements https://github.com/kubewarden/audit-scanner/issues/45
ci: Ship CRDS.tar.gz as part of GH releases. The file `CRDS.tar.gz` is already shipped if existing, but before this PR it didn't exist.
Untested. I can make a release in my fork against main, but I would need https://github.com/kubewarden/audit-scanner/pull/42 merged so I have viccuad/main clear :sweat_smile: .

ci: Ship CRDS.tar.gz as part of GH releases

---

CONTRIBUTING.md
README.md
cmd/root.go
internal/report/report.go
internal/report/report_test.go
internal/report/store.go
internal/report/store_test.go
internal/resources/fetcher.go
internal/scanner/scanner.go

Fix https://github.com/kubewarden/audit-scanner/issues/36
Save all reports to cluster.
Add a new `--print` flag: these flag prints the results to stdout as JSON, in addition to what the audit-scanner is doing.
Tested manually against cluster, see CONTRIBUTING.md.
This PR could include the first e2e tests for audit scanner (mocking policy-server). We also have k8s e2e tests listed as a different task on the epic.

feat: Save reports to cluster, add new `--print` flag to print them as JSON

---

.github/workflows/reusable-container-image.yml
Makefile
internal/report/report.go
internal/report/store.go
internal/scanner/scanner.go

Relates to https://github.com/kubewarden/helm-charts/issues/237
- chore: Provide more info logs
- ci: Test container image on build
- feat: Add ManagedBy label
- Set PolicyReportResult fields:
- severity: `"info"` if on monitor mode, empty otherwise
- scored: `true` if severity set
- rule: policy name
- category: either `"validating"` or `"mutating & validating"`
Tested locally out-of-cluster.
~~ClusterPolicyReport doesn't show on policy-reporter.~~ it does.

feat: Set PolicyReportResult fields

---

internal/constants/constants.go
internal/report/constants.go
internal/report/report.go
internal/report/report_test.go
internal/report/store.go
internal/report/store_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

The audit scanner now check if there is a policy evaluation result in the previous scan report for the same policy and resource version tuple. If there is, the result is copy into the new report.
Fix #44

feat: reuse report results.

---

.github/release-drafter.yml

Updates the release CI to publish the draft release created by release drafter instead of creating a new release. Therefore, we will use the nice changelog.

fix: publish release drafter draft release.

---

.github/workflows/container-build.yml
.github/workflows/release.yml
.github/workflows/reusable-container-image.yml

Updates the CI scripts updating the cosign-installer to v3. Thus, the cosign version now is v2. Which has breaking changes requiring some changes on how the command is called and removing the need of using environment variable to enable keyless signature.
Related to https://github.com/kubewarden/kubewarden-controller/issues/411

Updates cosign to v2.

---

cmd/root.go
cmd/root_test.go
internal/policies/fetcher.go
internal/resources/fetcher.go
internal/scanner/scanner.go

Fix https://github.com/kubewarden/audit-scanner/issues/52
- feat: Adjust flag behaviour
Not passing any flag: Scan cluster wide and all ns.
Passing both `--cluster` and `--namespace foo`: error.
- feat: Add new --skipped-ns flag, Add Fetcher.skippedNS
Add new flag of comma separated list of namespace names to be skipped.
Add new field to policies.Fetcher{}, Fetcher.skippedNs.
- feat: Add fetcher.GetAuditedNamespaces(), implement scan all ns
Tested locally. Example:
```
./bin/audit-scanner -l debug -u https://localhost:3000 -p -s "default,kubewarden"
```

feat: Scan all namespaces and cluster by default

---

.github/workflows/ci.yml
.golangci.yml
Makefile
internal/scanner/scanner.go

On all first runs, there aren't any previous policy reports. IMO this shouldn't be an error as it is expected.
On subsequent runs, this could also happen, if a user manually deletes policy reports. We should downgrade then to Info.
No need.

fix: Don't print errors on first run

---

.github/workflows/release.yml

Updates the release CI to check if the pushed tag has some text indicating a release candidate and set properly the flag to publish the release as final release or a candidate.
Related to https://github.com/kubewarden/policy-server/pull/497/files#r1268541197

fix: enable release candidates when required

---

CONTRIBUTING.md
internal/policies/fetcher.go
internal/resources/fetcher.go
internal/resources/fetcher_test.go
internal/scanner/scanner.go

Fix https://github.com/kubewarden/audit-scanner/issues/68
- [fix: Skip clusterwide resources in getResourcesForPolicies](https://github.com/kubewarden/audit-scanner/pull/73/commits/478f74fd621fb4860a5c2255948b966320c15570)
- [fix: Warn instead of panic when API resource not found or forbidden](https://github.com/kubewarden/audit-scanner/pull/73/commits/6682cbd733333ff2c24a516d77c2b78295f07580)
- Add tests
Added unit tests.
Performed manual integration tests when developing:
1. Deployed kubewarden helm charts from kubewarden/helm-charts@main:
```
helm upgrade -i --wait --namespace kubewarden --create-namespace kubewarden-crds ./charts/kubewarden-crds
helm upgrade -i --wait --namespace kubewarden --create-namespace kubewarden-controller ./charts/kubewarden-controller --set …
```

fix: Warn instead of panic when API resource not found or forbidden

---

cmd/root.go
internal/policies/fetcher.go
internal/policies/fetcher_test.go
internal/resources/fetcher.go
internal/scanner/scanner.go

Partial implementation of https://github.com/kubewarden/audit-scanner/issues/64
`--insecure-ssl` flag is false by default.
`--filepath-cacert` flag is "./policy-server-ca-cert" by default.
If `KUBEWARDEN_CACERT_PEM_POLICYSERVERS` is set, it will overwrite the
default and whatever value is passed as flag.
Tested locally. I don't see the need to add unit-tests, and integration tests aren't much useful either. I could add an e2e test without a kubeapi, where I provide a file that is not a PEM cert, and see it crash.
```console
$ audit-scanner --help
Scans resources in your kubernetes cluster with your already deployed Kubewarden policies.
Each namespace will have a PolicyReport with the outcome of the scan for resources within this namespace.
There will be a ClusterPolicyReport with results …
```

feat: Add `--insecure-ssl`, `--filepath-cacert` flags, consume ca cert

---

.golangci.yml
go.mod

Upstream is untagged, and we need to consume the PolicyReports v1alpha2.
Follow-up of https://github.com/kubewarden/audit-scanner/pull/86
Hopefully this will make the bot not try to bump that dep.
CI

deps: Pin wg-policy-prototypes

---

renovate.json

Supersedes https://github.com/kubewarden/audit-scanner/pull/89
We will see once we retrigger renovate

chore: Ignore wg-policy-prototypes in renovatebot 

---

.github/workflows/ci.yml
.github/workflows/container-image.yml
.github/workflows/fossa.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/sbom.yml
.github/workflows/sign-image.yml

Provide full version for GH actions

chore(deps): be explicit about the GH actions versions

---

CONTRIBUTING.md
cmd/root.go

Relates to https://github.com/kubewarden/helm-charts/pull/282.
No need.
This signifies that using `--output-scan` can be consumed by end users.
I have checked the source code to ensure that the audit-scanner binary doesn't print to stdout or stderr in a way that isn't JSON formatted (unless it suddenly catches a panic and one gets an exception).
Also, the current config of `golangci-lint` forbids `fmt.Println` and the like.
This should provide reasonable certainty that stdout can be consumed by end users.

refactor!: Rename `--print` flag to `--output-scan`

---

.github/workflows/release.yml

This is done by passing `make_latest` in the REST API update. See: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release
`make_latest` can be `true`, `false`, `legacy`, with legacy using semver, but I'm not sure from where it obtains the semver version (the release name?).
Hence setting it to `true` when not alpha, beta, or rc.
Relates to https://github.com/kubewarden/kubewarden-controller/issues/534.
Not tested.

ci: Set release as latest in GH releases page

---

internal/resources/admission_request.go

Fix https://github.com/kubewarden/audit-scanner/issues/148.
`RequestKind` matches the type of original API request, in the case that there's several kinds that match the same object (e.g: deployments can be modified via `apps/v1` ad `apps/v1beta1`), and conversion was performed.
The `AdmissionRequests` use `AdmissionRequest.Kind` to match the rule of the webhook registered for, hence `RequestKind` is there for book-keeping.
Set `RequestKind`, which gets consumed later on in policy-server to set the metrics baggage:
https://github.com/kubewarden/policy-server/blob/63c9f32052b7ced50b4007e8ce0b5ed27392aa7f/src/worker.rs#L226
Built an [audit-scanner image with the fix](https://github.com/users/viccuad/packages/container/test%2Faudit-scanner/154652198?tag=baggagefix) and tested that …

fix: Set `AdmissionRequest{}.RequestKind`

---

Dockerfile
Makefile

Fix https://github.com/kubewarden/audit-scanner/issues/119
Tested locally by running `ghcr.io/viccuad/test/audit-scanner:scratch ` in a cluster.
Checked `syft ghcr.io/viccuad/test/audit-scanner:scratch -vv`, which uses the go-module-binary-cataloger to find the deps:
```
[0001] DEBUG discovered 63 packages cataloger=go-module-binary-cataloger
(...)
```

feat: Build image with scratch instead of distroless

---

.github/workflows/sbom.yml

This fixes errors like "an artifact with this name already exists" in the container image build, after merging https://github.com/kubewarden/audit-scanner/pull/158.
To test this pull request, you can run the following commands:

ci: Deduplicate upload of artifacts

---

.github/workflows/release.yml
.github/workflows/sbom.yml

{upload,download}-artifact v4 don't accept uploading the same named artifact. Suffix their names with the arch, and download all of them at once into the same dir, as it was before.
Relates to https://github.com/kubewarden/audit-scanner/pull/160.
Tested on my fork: https://github.com/viccuad/audit-scanner/actions/runs/7261395579/job/19782800832

ci: Fix artifact upload and download

---

internal/log/policy_report_logger.go
internal/report/store.go
internal/report/store_kubernetes.go
internal/report/store_memory.go
internal/scanner/scanner.go

Fix #102
Instead of having a big log line containing all the content from the PolicyStore (which includes the `ClusterPolicyReport` and all the namespaced `PolicyReports`), this commit creates a `PolicyReportLogger` which logs all the relevant information per scanned resource.
I didn't create any tests for this class because it's just responsible for logging. However, I did test this manually by running:
```
./bin/audit-scanner --store memory --policy-server-url "https://localhost:8443" --insecure-ssl --output-scan
```
eg.:
```
{"level":"info","dict":{"policy":"cap-service-external-ip","rule":"service-external-ip","result":"pass","message":"","resource_api_version":"v1","resource_kind":"Service","resource_namespace":"some-namespace","resource_name":"some-pod","resource_version":"780797213" …
```

feat: adds logging per `(Cluster)PolicyReport` result

---

go.mod
go.sum
internal/policies/filter_test.go
internal/resources/fetcher.go
internal/resources/fetcher_test.go

Fix https://github.com/kubewarden/audit-scanner/issues/168
When building the corpus of resources that match the policy rules,
correctly skip those that are unexistent (e.g: "*/v1").
Emit a warning instead. The scan will still process the correct resources that match the provided GVR. Example:
```
{"level":"info","time":"2024-01-08T14:49:26+01:00","message":"querying PolicyServers at https://localhost:3000 for debugging purposes. Don't forget to start `kubectl port-forward` if needed"}
{"level":"warn","time":"2024-01-08T14:49:26+01:00","message":"connecting to PolicyServers endpoints without validating TLS connection"}
{"level":"info","namespace":"default","time":"2024-01-08T14:49:26+01:00","message":"namespace scan started"}
{"level":"info","namespace":"default","dict":{"policies to …
```

fix: Correctly skip unexistent resources 

---

internal/scanner/scanner.go

Set the content type to `application/json` when calling the policy server.
The API now is checking the content type, if not set this will result in a 415 error.
Also, check that the status code is 200 instead of `< 299`
tested with e2e tests and unit tests are passing

fix: set content-type to application/json when calling the policy-server

---

.github/workflows/ci.yml
Makefile
coverage/unit-tests/.gitignore

Fix https://github.com/kubewarden/audit-scanner/issues/187
- Change `make unit-tests` to save coverage files.
- Create new `coverage/unit-tests/` folder.
- Add codecov upload step to ci.yml. It uploads the coverage files resulting from running `make unit-tests`. Needs `CODECOV_ORG_TOKEN`, already set up.
CI, PR should get a "welcome to codecov" message, and audit-scanner appear under https://app.codecov.io/github/kubewarden/.

ci: Enable codecov

---

internal/report/report.go
internal/report/report_test.go
internal/scanner/scanner_test.go

The code which builds the PolicyReportResult does check if the Result field from the AdmissionRespose type is nil. Causing a nil pointer dereference. This field is optional and it can be nil. Specially if the policy result is "allowed" where there is not further details about the result of the evaluation.
This commit fixes this issue by checking if the Result field has something before trying to get the possible error message from the policy.
Fix #212 
I've added a new unit test to cover this bug.
```shell
make unit-tests
```

fix(report): Result field is optional.

---

go.mod
go.sum
internal/scanner/scanner.go

This PR implements parallel audit requests to the policy server.
The parallelism is currently set to 100 requests, but in the future, we could expose this value to the user through the CLI so that it can be tuned. 
Before the fix on a cluster with ~300 resources and 15 policies:
```
Percent of CPU this job got: 79%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:41.24
```
After the fix
```
Percent of CPU this job got: 109%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:30.42
```
In the case of slower policies (for instance policies using context-aware capabilities) is safe to assume that the elapsed time difference should be higher.

feat: parallel audit requests

---

README.md
internal/report/constants.go
internal/report/report.go
internal/report/report_test.go

Adds the policy name and the policy namespace (if any) to result properties

fix: add policy name and policy namespace to result properties

---

internal/report/constants.go
internal/report/report.go
internal/report/report_test.go

This allows us to discriminiate policyreports between pre 1.11 (missing label), and 1.11 (having label), plus helping for future changes.
Relates to  https://github.com/kubewarden/helm-charts/issues/408
CI

feat: Add new `kubewarden.io/policyreport-version: v2` label

---

Dockerfile

Consuming `github.com/kubewarden/kubewarden-controller v1.12.0` brings a bump to Go 1.22 just as it is in the controller.
This is needed to build releases.
CI.

deps: Bump golang to 1.22 in Dockerfile builder layer

---

Makefile

Build a statically linked binary whan `make build` is invoked.

Update build target of makefile

---

ARCHITECTURE.md

Explain how the audit-scanner performs the scan.
1. Instead of doing Namespace auditing sequentially, allow for parallel auditing of namespaces. Expose a flag for that
2. Inside of a Namespace, keep auditing resources in parallel, but instead of hard coding the number of resources being audited in parallel, expose a flag for that
3. When auditing a specific resource (like a specific `Pod`), instead of evaluating each policy sequentially, evaluate them in parallel. Expose a flag for that

docs: add ARCHITECTURE.md

---

ARCHITECTURE.md
README.md
cmd/root.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Change how the audit process is done, allowing more parallilazion if wanted by the user.
This PR adds these new flags (I'm open to change their names, I'm not super fond of them):
- `--parallel-namespaces`: how many Namespaces can be audited in parallel. Default is 1.
- `--parallel-resources`: how many resources can be audited in parallel. Default is 50.
- `--parallel-policies`: when auditing a specic resource, how many policies can be invoked in parallel. Default is 10.
By tuning these values, the user has direct control over how many HTTP requests are sent to the policy server(s) at the same time.
For example, `--parallel-namespaces 2 --parallel-resources 100 --parallel-policies 10` translates to a maximum of `2 * 100 * 10 = 2000` HTTP requests at the same time.
Given the following …

parallelize everything

---

internal/k8s/client.go
internal/report/store.go
internal/scanner/scanner.go

The keys of structured logs should not have spaces inside of them. That makes querying the logs harder.

fix: structured logs should not have spaces inside of keys

---

internal/policies/client.go
internal/policies/client_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Fix https://github.com/kubewarden/audit-scanner/issues/307
For policies that target an unknown GVR, or for which no valid
policy-server URL can be constructed, emit error logs and count them as
errored. Continue with the audit scan.
This is a regression fix from previous audit-scanner 1.11 refactor.
For that, add new `Policies.ErroredNum` field. This errored tally will get
printed in the logs, but can't be printed in (Cluster)PolicyReports, as there's
no report created for an unknown unexistent resource.
Note that policies that target an unknown GVR may be incorrectly configured,
or may have been correctly configured against a CRD, but the CRD has been removed by now.
Added unit tests, CI.
With the current (Cluster)PolicyReport data structures, it isn't possible to save an error on them …

fix: Skip policies with unknown GVR or policy-server URL

---

.github/workflows/ci.yml
.golangci.yml
Makefile
cmd/root.go
internal/policies/client.go
internal/report/store_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Updates the Go lang linter to stricter configuration. Also, updates the audit scanner code to make the linter happy again.
Fix https://github.com/kubewarden/kubewarden-controller/issues/778
The `.golangci.yml` configuration file is the same of used in the [controller](https://github.com/kubewarden/kubewarden-controller/pull/807)
```shell
make lint
```

feat: use stricter go linter configuration.

---

internal/report/report_test.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go

Fix  https://github.com/kubewarden/audit-scanner/issues/337
When we get all auditable policies for a namespace (or clusterwide) we
have a number of skipped policies (those skipped because of constraints
like no * in GVR) and a number of errored policies (unknown GVR for
example).
Propagate those numbers to the creation of the (Cluster)PolicyReport
for its `spec.Summary`.
Note: when we audit resources later on, we can have errored or skipped
policies, those get added to `spec.Summary` at that time.
CI

fix: Propagate skipped,errored numbers from audited policies

---

internal/report/report.go
internal/report/report_test.go
internal/scanner/scanner.go

If not, errors on creating an AdmissionReview get logged but we continue. Given that we don't have an AdmissionReview, we would panic on `report.newPolicyReportResult()`.
Example:
```console
{"level":"error","error":"unexpected status code: 500 body: {\"message\":\"Something went wrong\",\"status\":500}","response":{"admissionRequest-name":"nginx-with-secrets","policy":"pod-image-signatures","resource":"nginx-with-secrets"},"time":"2024-09-11T16:34:41+02:00","message":"error sending AdmissionReview to PolicyServer"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b59592]
goroutine 163 [running]:
github.com/kubewarden/audit-scanner/internal/report.newPolicyReportResult({0x23f4488, 0xc0001c1c00}, 0x0, …
```

fix: Correctly log errors on creating AdmissionReview instead of panic

---

cmd/root.go
internal/scanner/config.go
internal/scanner/scanner.go
internal/scanner/scanner_test.go
internal/testutils/testutils.go

Part of: #462 
This PR introduces the `client-cert` and `client-key` flags, which specify the certificate file paths for mTLS communication with PolicyServer endpoints. 
Additionally, it refactors the `Scanner` constructor by introducing a `Config` type to manage the growing number of constructor parameters.

feat: add mTLS support

---

.github/workflows/ci.yml

Updates the golang linter used in the CI workflow to v2.1.0.
Required to make the CI [here](https://github.com/kubewarden/audit-scanner/pull/526) happy

chore: updates golang linter.
